### ISSUE TITLE
Choose File open 2 windows

### ISSUE THREAD

**Issue by TheeeEVan** [jaketrent/demo-electron-directory#2]
When I click choose file it opens 2 windows, a chosen folder, and a choose file.

**Comment by rthangam** [comment]
Yes any fix for this ?

**Comment by rthangam** [comment]
I just modifined the renderer.js to this one and it works fine.

document.getElementById('dirs').addEventListener('click', (evt) => {
  evt.preventDefault();
    window.postMessage({
      type: 'select-dirs'
    })
  })

**Comment by jaketrent** [comment]
Hey, thanks for the ping and the modified code snippet. I applied the snippet and committed. This should be addressed now.

As another data point, on macos at least, I didn't experience the two window problem before or after this modification.

Take care, ya'll.
